#   NumPy Notebook

## What is NumPy

* It's designed to work with arrays. Basic Python arrays has limited functionalities Which means you can not work with advanced mathematical operations with basic arrays.

* NumPy can perform various complex operations on arrays including shape manipulation, basic linear algebra, random simulation and more.

The main structure of NumPy is object known as the ndarray. Its an multidimentional array of elements, which typical is an array itself.

Datasets in ML are frequently stored as 2D ndarrays
Therefore, familiarity with NumPy is essential

## 2.2 Importing the NumPy Library¨
to work with NumPt, it needs to be imported
its customary to use np as the alias for NumPy


In [23]:

#   2.2 Importing NumPy
#   Importing Python Repositories
import numpy as np


# 2.3 Creating a NumPy Array
There is two ways to create an ndarray.
The first is to convert a Python like array Structure (list / tuple)
The Second way is to directly use np.array([list values])

# Example

list1 & list2 are similar, except list1 har one set of square brackets (1Dimentional array)
while the second one has two square brackets (2 Dimentional array). list3 has three nested lists with four elements (2 Dimentional arrays)

After the list declearation we pass them to the NumPy array() to convert them into ndarrays.
The output for checking the type of an array indicates the list has been successfully converted into NumPy arrays. By checking the output of ndarray shape inform us the number of elements in it


2D arrays is represented as a tuple with two values
[[1,2,3],[4,5,6]](2,3) notifies us that the array consists of x rows and x columns.

To create an array from the scratch we use the buildt-in function linspace(start, stop, num).
It generates a floating point numbers by default (Jupyter prints decimals as comma)

In [24]:

#   2.2 Importing NumPy
#   Importing Python Repositories
import numpy as np

#   Example
#   Initializing lists

#   Initializing 1D Array
list1 = [1, 2, 3, 4, 5 , 6, 7, 8]

#   Initializing 2D Array
list2 = [   [1, 2, 3, 4, 5], 
            [6, 7, 8, 9, 10]]

list3 = [
            [list1.copy()], 
            [10, 20, 30, 40], 
            [100, 200, 300, 400]]

#   Converting lists into numpy arrays

ar = np.array(list1)
ar1= np.array(list2)
ar2= np.array(list3)
ar3 = np.linspace(0,10,15)

print(f'Checking which type the NumPy arrays is\n{type(ar)}\n\nSecond list:\n{type(ar1)}\n\nThird list:\n{type(ar2)}\n')

print(ar.shape, ar1.shape, ar2.shape)
print(ar1[0,1])

Checking which type the NumPy arrays is
<class 'numpy.ndarray'>

Second list:
<class 'numpy.ndarray'>

Third list:
<class 'numpy.ndarray'>

(8,) (2, 5) (3,)
2


C:\Users\krigj_b\AppData\Local\Temp\ipykernel_20812\3688980885.py:24: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar2= np.array(list3)


# 2.4 Selecting Data from a NumPy Array

Acccess NumPy Array in the same way as Python by using indexes. 
Indexes starts from 0, and negative values starts from the back.

2D Arrays can be accsessed the same way as 2D lists, and by adding [0,1] a second value
The first value access the first element in the array, the second element is accessed by using a second value

By using the [start:stop:step] notation we can slince the NumPy array it can be used in 2D ndarrays also
[0:2,2:4]. Slice before the comma, selects the rows, while the slice after selects the columns

tip :
Working with 2D arrays like a table.


In [29]:
#   Example

print(f'Printing output of the np array\n{ar[0]}\n {ar[-1]}')
print(f'Printing a 2D array:\n {ar1[0][1]}\n {ar1[0,2]}')
print(f'Slicing a 1D array:\n {ar[1:3:2]}\n Slice a 2D array\n {ar2[0:2,2:4]}\n')

Printing output of the np array 1
 8
Printing a 2D array:
 2
 3


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

# 2.5 ndarray Methods

## ndarray Class

The methods sum() & mean() gives us the sum and mean of an array.

### sum()

If sum() is used without specifying the axis it returns the sum of all elements in the array. If we specify axis=0, it sums the elements in each column. axis=1 sums the elements in each row.

### reshape()

reshapes to a NumPy array without modifying the data.
by using reshape() we can reshape the array 


it is necessary to know how to reshape 1D arrays into 2D arrays, certain methods in Scikit-Learn library requires 2D arrays

**Tip**

allowing the reshape method to interfer the shape for us, by passing (n,-1) or (-1, n) (row, column)

In [33]:

#  2.5 ndarray methods

arg = ar1.sum()
arg1 = ar1.sum(axis=1)
arg2 = ar1.sum(axis=0)
print(f'Sum :\n{arg}\n\nSums the rows:\n{arg1}\n\nSums the columns:\n{arg2}\n')

#  Rehapeshaping 1D list, one row, 9 columns


arg = ar.reshape(4,2)
print(f'Original array:\n{ar}\n\nRechaping the 1D list:\n{arg}\n')


Sum :
55

Sums the rows:
[15 40]

Sums the columns:
[ 7  9 11 13 15]

Original array:
[1 2 3 4 5 6 7 8]

Rechaping the 1D list:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]



#   2.6 NumPy Functions

##  NumPy routines
concatenate() is a commonly used method in NumPy, it's used to join arrrays, it can be specified to either join along axis 0 & 1. Axis 0 combines the rows and requires the arrays to have the same number of columns. This is the default value, while using axis 1 combines the columns and requires the arrays to have the same number of rows.

##   NumPy Wrapper functions

Some of the NumPy functions are wrappers around coresponding medhods in the ndarray class
e.g reshape()

### What is a Wrapper function
A wrapper is a function whose main purpose is to call another function or method. 
We can use the wrapper in two ways, the np.reshape() and arr.reshape()



In [37]:
# 2.6    Numpy FUnctions
arr = np.array([[1, 2], [3, 4]])
arr1 = np.array([[5, 6], [7, 8]])
arr2 = np.array([[9, 10], [11, 12], [13, 14], [15,16]])

com = np.concatenate((arr, arr1))
rom = np.concatenate((com, arr2), axis=1)

print(f'Arrays to concatenates\n {arr}, {arr1}\nConcatenates the arrays into \n{com}')
print(f'Concatenates the Three arrays into \n{rom}')

#   NumPy Wrapper functions
r = arr.reshape(2,-1)
r1 = np.reshape(arr,(2,-1))
print(f'{r}\n{r1}')

Arrays to concatenates
 [[1 2]
 [3 4]], [[5 6]
 [7 8]]
Concatenates the arrays into 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenates the Three arrays into 
[[ 1  2  9 10]
 [ 3  4 11 12]
 [ 5  6 13 14]
 [ 7  8 15 16]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
